### ISSUE TITLE
Not related to polymon.

### ISSUE THREAD

**Issue by Apache97** [polyscone/polymon#1]
Hi. Sorry I don't know where else to reach out to you.

I wanted to ask about the software renderer. https://youtu.be/C1ORRy_TgTo

Do you plan to put it in a repo? Or if you prefer to host it somewhere private like google drive etc. It doesn't matter if the implementation is not clean, I would still like to take a look and learn a few things. Thanks.

**Comment by polyscone** [comment]
@Apache97 
That's ok
The code has no dependencies, so it runs directly on the Win32 API and nothing else, but if that's ok with you can add me on Disrcord or something and I'll send the code zipped up for you
Username is Polyscone#9258

**Comment by Apache97** [comment]
Thanks!
